---
- name: set vars
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: set var
      local_action:
        module: add_host
        name: pyton
        ansible_ssh_host: "192.237.219.96"
        ansible_ssh_pass: "F00 man choo!"
        ansible_ssh_user: root
        groups: webs

- name: get hostname
  hosts: webs
  tasks:
    - name: get hostname
      shell: hostname
